server:
  port: 8090
spring:
  application:
    name: CONFIGSSERVICE
  cloud:
    consul:
      port: 8500
      host: localhost
    config:
      server:
        git:
          uri: https://gitee.com/ljzend/spirngcloud_configs.git
          username: ljzend
          password: ******
          default-label: master
